require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/paynows", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Paynow. As you add validations to Paynow, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Paynow.create! valid_attributes
      get paynows_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      paynow = Paynow.create! valid_attributes
      get paynow_url(paynow)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_paynow_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      paynow = Paynow.create! valid_attributes
      get edit_paynow_url(paynow)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Paynow" do
        expect {
          post paynows_url, params: { paynow: valid_attributes }
        }.to change(Paynow, :count).by(1)
      end

      it "redirects to the created paynow" do
        post paynows_url, params: { paynow: valid_attributes }
        expect(response).to redirect_to(paynow_url(Paynow.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Paynow" do
        expect {
          post paynows_url, params: { paynow: invalid_attributes }
        }.to change(Paynow, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post paynows_url, params: { paynow: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested paynow" do
        paynow = Paynow.create! valid_attributes
        patch paynow_url(paynow), params: { paynow: new_attributes }
        paynow.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the paynow" do
        paynow = Paynow.create! valid_attributes
        patch paynow_url(paynow), params: { paynow: new_attributes }
        paynow.reload
        expect(response).to redirect_to(paynow_url(paynow))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        paynow = Paynow.create! valid_attributes
        patch paynow_url(paynow), params: { paynow: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested paynow" do
      paynow = Paynow.create! valid_attributes
      expect {
        delete paynow_url(paynow)
      }.to change(Paynow, :count).by(-1)
    end

    it "redirects to the paynows list" do
      paynow = Paynow.create! valid_attributes
      delete paynow_url(paynow)
      expect(response).to redirect_to(paynows_url)
    end
  end
end
